<?php

namespace Acme\DemoBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AcmeDemoBundle:Product p ORDER BY p.name ASC '
            )
            ->getResult();
    }

    public function findByIdJoinedToCategory()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, c FROM AcmeDemoBundle:Product p JOIN p.category c 
                  WHERE p.id = :id'
            )->setParameter('id', '13');

        try{
            return $query->getSingleResult();
        }catch(\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }
}
