<?php

namespace Acme\ManbaBundle\Repository;

/**
 * MttRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MttRepository extends \Doctrine\ORM\EntityRepository
{
}
